### ISSUE TITLE
自己主張がちょっと足りていない件

### ISSUE THREAD

**Issue by hitobb** [kaminuma/nico#1]
自己紹介が書かれていない不具合を発見しました。
README.mdにいろいろ記載してみてくださいｗ

※直接、編集できます。

**Comment by kaminuma** [comment]
失礼しました。
自己主張強い系男子で頑張っていこうと思いますので、
今後とも宜しくお願い致します。

**Comment by kaminuma** [comment]
早めに寝ないといけなかった！
というバグを見つけたので、明日か明後日に書きます（笑

**Comment by hitobb** [comment]
ちなみにクローズ後もコメントできるｗ

**Comment by hitobb** [comment]
意外と便利w

**Comment by kaminuma** [comment]
クローズされてるから、全然気づかなかったｗｗ
