### ISSUE TITLE
readme.md以外のファイルがアップされていない件

### ISSUE THREAD

**Issue by hitobb** [kaminuma/nico#2]
ステップ２！
自分のローカルファイルをGitHubに保存してみようｗ

（機能が足りていないですけど）
最初はこのツールがシンプルでわかりやすいのでオススメです。

https://desktop.github.com/

**Comment by kaminuma** [comment]
ちょっと出かける前にやっつけでやったのでネタとか全然仕込めてません。
githubDesktopいじってみました。

**Comment by hitobb** [comment]
ファイルのアップロードを確認しました。
こちらのケースは、私の権限でクローズしますねｗ

**Comment by hitobb** [comment]
閉じた本人だと、再オープンが可能

**Comment by hitobb** [comment]
もう一回、閉じますねｗ

**Comment by kaminuma** [comment]
開けてみた！！
そしてそっと閉じる。
